# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_artist_one_sentence_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description_title',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
    ]
