# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_artist_description_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(default=b'1 X 1', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default=b'Paint', max_length=64),
        ),
        migrations.AddField(
            model_name='item',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
