# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_auto_20160722_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buy_link',
            field=models.URLField(default=b'', max_length=256),
        ),
    ]
