# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20160728_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
